Add bot resource
coderdojobraga/bokken pull request #145
Opened 2022-11-10 10:09 UTC by danielsp45

This PR creates a bot schema, in order to register bots that are allowed to make request to the API with a specific API key.

2022-11-17 21:25 UTC, RuiL1904 reviewed
In order to best test this, can you add endpoints to postman? 🙏🏼

2022-11-19 19:11 UTC, danielsp45 commented
> In order to best test this, can you add endpoints to postman? 🙏🏼

Sure, OMW 💪🏻

2022-12-03 21:18 UTC, RuiL1904 requested changes
Can you remove the .DS_Store file? 🙏🏼

2022-12-03 21:26 UTC, RuiL1904 commented on lib/bokken/accounts/bot.ex
> +    |> unique_constraint(:name)
I don't think the `name` should be unique.

2022-12-03 21:26 UTC, RuiL1904 commented on lib/bokken/accounts/user.ex
> +    field :discord_id, :string
It would be nice, in the future, to tie this to the user socials (specifically discord one). What's your opinion? 🙏🏼

2022-12-03 23:59 UTC, RuiL1904 approved these changes

2022-12-04 00:43 UTC, merged