Add organizer name
coderdojobraga/bokken pull request #152
Opened 2022-12-21 09:57 UTC by MarioRodrigues10

2022-12-21 10:01 UTC, RuiL1904 requested changes

2022-12-21 10:01 UTC, RuiL1904 commented on priv/repo/migrations/20210421205214_create_organizers.exs
> +      add :last_name, :string, null: false
You need to create an ALTER migration. Don't forget that bokken is already in prod 😅

2022-12-21 10:56 UTC, ruioliveira02 requested changes

2022-12-21 10:56 UTC, ruioliveira02 commented on priv/repo/migrations/20221221100911_alter_organizers.exs
> +      add :last_name, :string, null: false
We are running in production, meaning the table organizers already has data, which we cannot erase. This migration will fail as the new collumns will always default to null. You must specify a default value for it to work (or make it nullable, but I don't think it is a good idea)

2022-12-22 14:46 UTC, RuiL1904 approved these changes

2022-12-26 13:50 UTC, ruioliveira02 approved these changes

2022-12-26 13:50 UTC, merged