Implement organizer dashboard
coderdojobraga/bokken pull request #153
Opened 2023-01-05 19:08 UTC by RuiL1904

2023-01-15 15:19 UTC, MarioRodrigues10 requested changes

2023-01-15 15:19 UTC, MarioRodrigues10 commented on lib/bokken/accounts.ex
> +  def update_mentor_and_user(mentor_params, user_params) do
Try to make this handle more error cases such has ```Mentor and user not found``` and ```An error occurred while fetching the user or mentor```

2023-01-15 15:19 UTC, MarioRodrigues10 commented on lib/bokken/accounts.ex
> +  def update_ninja_and_user(ninja_params, user_params) do
Make this handle more error cases such has ```Ninja and user not found``` and ```An error occurred while fetching the user or mentor```

2023-01-20 00:01 UTC, MarioRodrigues10 submitted a review, later dismissed
Good Job ! :muscle:

2023-01-20 00:57 UTC, MarioRodrigues10 requested changes
Also there's a bug when i try to fetch mentors, ninjas, guardians in frontend
```c
 function AdminView.__resource__/0 is undefined
```

2023-01-20 00:57 UTC, MarioRodrigues10 commented on lib/bokken_web/controllers/admin_controller.ex
> +defmodule BokkenWeb.AdminController do
Protect the endpoints please with ```when is_organizer(conn)```

2023-01-21 09:10 UTC, MarioRodrigues10 submitted a review, later dismissed
LGTM ! :rocket:

2023-01-21 17:07 UTC, MarioRodrigues10 commented
There's a 500 error when we try to use the endpoint to fetch mentors on the route ``` /admin/lectures/new ```.
Please try to fix that :pray:

2023-01-23 10:54 UTC, MarioRodrigues10 approved these changes, later dismissed
Good Job !

2023-02-06 10:50 UTC, MarioRodrigues10 submitted a review, later dismissed

2023-02-19 01:29 UTC, MarioRodrigues10 approved these changes, later dismissed

2023-02-19 19:45 UTC, nelsonmestevao commented on lib/bokken_web/router.ex
> +      get "/users", AdminController, :index_users
I think you should respect REST. And split the controller into smaller modules.

```elixir
scope "/users", AdminController do
  get "/", User, :index
  put "/", User, :update
end
```

If you think the endpoints are really simple, you can even define it inside the same controller file. Like this:

```elixir
defmodule AdminController do
  defmodule User do
  ...
  end
  
  defmodule Ninja do
  ...
  end
  ...
```

2023-02-19 19:47 UTC, nelsonmestevao commented on lib/bokken_web/router.ex
> +      get "/users", AdminController, :index_users
Basically, I think you should be able to use the `resources` macro.

```elixir
resources "/user", only: [:index, :update]
```

2023-02-19 20:06 UTC, RuiL1904 commented on lib/bokken_web/router.ex
> +      get "/users", AdminController, :index_users
It's ironic that the branch name contains "rest" and I'm not implementing it 😅
Will implement it 🙏🏼

2023-02-24 10:27 UTC, ruioliveira02 reviewed
Add the new endpoints to Postman pls :pray:

2023-03-01 12:08 UTC, ruioliveira02 reviewed
Just add the endpoints to Postman :pray: We are refactoring the tests anyway, so I'm not too bothered by them not being here

Also, could you bump the version in `mix.exs` to `1.0.6` pls?

2023-03-03 10:12 UTC, ruioliveira02 approved these changes

2023-03-03 11:04 UTC, merged